# Generated by Django 5.0.6 on 2024-07-15 19:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('notification_subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_arn', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organization.organization')),
            ],
            options={
                'db_table': 'notification_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_content', models.TextField()),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organization.organization')),
                ('notification_subscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notifications.notificationsubscription')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
