# Generated by Django 5.0.6 on 2024-07-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsubscription',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('OTHER', 'Other')], max_length=100, null=True),
        ),
    ]
