import os


class RabbitMQParams:
    # RabbitMQ URLs
    NOTIFICATIONS_RABBITMQ = {
        'HOST': os.getenv('NOTIFICATIONS_RABBITMQ_HOST'),
        'USERNAME': os.getenv('NOTIFICATIONS_RABBITMQ_USERNAME'),
        'PASSWORD': os.getenv('NOTIFICATIONS_RABBITMQ_PASSWORD'),
        'EXCHANGE': os.getenv('NOTIFICATIONS_RABBITMQ_EXCHANGE'),
        'EXCHANGE_TYPE': os.getenv('NOTIFICATIONS_RABBITMQ_EXCHANGE_TYPE'),
        'QUEUE_NAME': os.getenv('NOTIFICATIONS_RABBITMQ_QUEUE_NAME'),
        'ROUTING_KEY': os.getenv('NOTIFICATIONS_RABBITMQ_ROUTING_KEY'),
    }

    NOTIFICATIONS_SUBSCRIPTION_RABBITMQ = {
        'HOST': os.getenv('NOTIFICATIONS_SUBSCRIPTION_RABBITMQ_HOST'),
        'USERNAME': os.getenv('NOTIFICATIONS_SUBSCRIPTION_RABBITMQ_USERNAME'),
        'PASSWORD': os.getenv('NOTIFICATIONS_SUBSCRIPTION_RABBITMQ_PASSWORD'),
        'EXCHANGE': os.getenv('NOTIFICATIONS_SUBSCRIPTION_RABBITMQ_EXCHANGE'),
        'EXCHANGE_TYPE': os.getenv('NOTIFICATIONS_SUBSCRIPTION_RABBITMQ_EXCHANGE_TYPE'),
        'QUEUE_NAME': os.getenv('NOTIFICATIONS_SUBSCRIPTION_RABBITMQ_QUEUE_NAME'),
        'ROUTING_KEY': os.getenv('NOTIFICATIONS_SUBSCRIPTION_RABBITMQ_ROUTING_KEY'),
    }
