# Generated by Django 5.0.6 on 2024-07-15 19:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_account_id', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'organizations',
                'unique_together': {('organization_name',)},
            },
        ),
    ]
